### ISSUE TITLE
isPending property not available

### ISSUE THREAD

**Issue by TechSis01** [TanStack/tanstack.com#108]
The documentation specifies that isPending or status === 'pending' - The query has no data yet
But logging out the object returned by useQuery, isPending is not part of properties like it is specified in the documentation.

**Comment by TkDodo** [comment]
should work, show a codesandbox please

**Comment by crutchcorn** [comment]
Closing, as this appears to be an issue intended for TanStack Query, and this repo is more specifically for the website.
