### ISSUE TITLE
Algolia search results for Query only route to v4 docs

### ISSUE THREAD

**Issue by RamsayRomero** [TanStack/tanstack.com#116]
When searching the Tanstack Query docs with the Algolia search bar, it only searches on the v4 version of the docs, no matter what docs version you have currently selected. This is especially frustrating when trying to search for features that have a new name in v5. The search results are empty. It is also frustrating if I click on a search result and I am routed to the v4 version of the docs as I won't realize I'm browsing the incorrect version of the docs. I looked into fixing this myself but it seems like the configuration is handled through the Algolia web interface?

**Comment by IdoBouskila** [comment]
Hi, They're aware 👇🏼

              we're aware and working on it. It's an upstream issue with Algolia DocSearch

_@TkDodo in https://github.com/TanStack/query/issues/6325#issuecomment-1799062015_

**Comment by tannerlinsley** [comment]
Fixed
