### ISSUE TITLE
Codesandbox plugin on site 'tanstack.com/query' takes forever to load

### ISSUE THREAD

**Issue by okay-head** [TanStack/tanstack.com#119]
I'm using Firefox 119.0.1 (64-bit) on an intel i5 and when i scroll to the section where it contains a codesandbox plugin, it produces a blank empty canvas. 

![image](https://github.com/TanStack/query/assets/68184623/0762ab8a-818e-43b0-86ee-24e05a680b19)

Here is the site for reference https://tanstack.com/query/v3/

Even if it loads, pressing the tabs for solid, vue etc will result in the black canvas yet again.

**Comment by TkDodo** [comment]
they work fine on latest: https://tanstack.com/query/latest/

**Comment by okay-head** [comment]
I guess it's not much of an issue then
