### ISSUE TITLE
Why you have Tinder tracking on your website? It seems a little bit unrelated. But  just my personal opinion. 

### ISSUE THREAD

**Issue by andreadito** [TanStack/tanstack.com#137]
![image](https://github.com/TanStack/tanstack.com/assets/2083714/131b56ab-a57e-4ef0-83aa-7283d3afd758)

Browser: Edge
OS: MacOs

**Comment by tannerlinsley** [comment]
This is likely a misattribution of the Scarf.sh telemetry pixel. @avipress?

**Comment by tannerlinsley** [comment]
This is likely a misattribution of the Scarf.sh telemetry pixel. @aviaviavi?

**Comment by aviaviavi** [comment]
Hmm I suppose that's possible but it sounds unlikely. @andreadito  are you using any extensions that could be causing this?

**Comment by aviaviavi** [comment]
Also, could you verify if the request to static.scarf.sh went through? If so, it's something else.

**Comment by andreadito** [comment]
> Scarf.sh

No I'm not using any extension - used in private mode 
I don't see any request to static.scarf.sh at least in the home page

**Comment by tannerlinsley** [comment]
I’ve scoured my site and can only find references to Google analytics and scarf. I’m so mega curious how you’re seeing Tinder. It’s so random.

**Comment by tannerlinsley** [comment]
I think I figured it out. If you block all of the carbonads domains/requests in devtools (the developer-centric ad network I use on TanStack.com), then "Tinder" no longer shows up as a blocked tracker. 

My best guess is that whatever registry Edge is using has somehow mislabeled carbon ads as Tinder. 

I'll contact them directly about this, and also ping @buysellads here so they can investigate further.

**Comment by tannerlinsley** [comment]
From BuySellAds:

> Hi Tanner,

> I can confirm that Carbon script has been mislabeled. Microsoft Edge uses [Disconnect.me](https://github.com/TanStack/tanstack.com/issues/Disconnect.me) block list for their protection. https://github.com/disconnectme/disconnect-tracking-protection/blob/master/services.json that they are using. I will report an issue to see if they can remove it.
