### ISSUE TITLE
Malformed algolia search results

### ISSUE THREAD

**Issue by timmyichen** [TanStack/tanstack.com#156]
I think this is different from #138, but the algolia search results have a malformed URL.

For example, searching for `useMutation`:
```
https://tanstack.com/query/v4/docs/react/reference/useMutation <-- Algolia search result links to
https://tanstack.com/query/v4/docs/framework/react/reference/useMutation <-- Actual docs page found in sidebar
```

Going to the malformed URL without `/framework/` just redirects to the docs homepage, which can be confusing for some folks.  I don't think the fix is within this repo (as opposed to whatever Algolia has cached) but happy to open a PR if I'm wrong.

**Comment by lachlancollins** [comment]
Hi @timmyichen , I think this is probably something Algolia has cached. I'm going to see if I can temporarily fix this. See also: https://github.com/TanStack/query/issues/6772

**Comment by timmyichen** [comment]
Thanks for the quick fix!
