### ISSUE TITLE
The code sandbox is not working for TanStack Query 

### ISSUE THREAD

**Issue by Barlow1** [TanStack/tanstack.com#16]
The code sandbox is not working for TanStack Query 
Error:  
``` DependencyNotFoundError
Could not find dependency: '@tanstack/react-query' relative to '/src/index.js'
```

![image](https://user-images.githubusercontent.com/9888728/179086635-63ffd922-cb03-4d62-85e1-9d875024e23f.png)

**Comment by tannerlinsley** [comment]
Should be fixed now
