### ISSUE TITLE
Old manual version redirects don't work as expected

### ISSUE THREAD

**Issue by lachlancollins** [TanStack/tanstack.com#164]
## Problem

The `handleRedirects` functions in `table.$.tsx`, `router.$.tsx`, `query.$.tsx`, and `virtual.$.tsx` do not work as expected, since a lower-level layout has priority on redirecting these paths.

For example, if you visit `/table/v7/docs/api/useColumnOrder`:

```
/table/v7/docs/api/useColumnOrder
/table/latest/docs/api/useColumnOrder #1st redirect
/table/latest/docs/introduction #2nd redirect
```

See discussion on #158 

## Potential Solution

The `handleRedirects` functions should probably be moved to the `docs.$.tsx` level, where they can run before the `loadDocs` function. Maybe the original functions could be moved to and exported from the project folders?

**Comment by fulopkovacs** [comment]
> The handleRedirects functions should probably be moved to the docs.$.tsx level, where they can run before the loadDocs function. Maybe the original functions could be moved to and exported from the project folders?

Good ideas, I'll make a PR!
