### ISSUE TITLE
preview broken at `tanstack.com/virtual`

### ISSUE THREAD

**Issue by kosovojs** [TanStack/tanstack.com#174]
currently seeing this error at `https://tanstack.com/virtual/latest`

![image](https://github.com/TanStack/tanstack.com/assets/46270007/f6a9686e-5722-4c5b-a565-e20236a8cc01)

**Comment by fulopkovacs** [comment]
I can confirm that I do see this error when I visit https://tanstack.com/virtual/latest/docs/framework/react/examples/simple, but there is no `react/simple` example in the virtual repo either (see https://github.com/TanStack/virtual/tree/main/examples/react).

Did you experience when you visited the same url? If yes, could you tell me how you got to that page? Is there a link in the docs somewhere?

**Comment by kosovojs** [comment]
Not sure if i understood you correctly, but...

> Did you experience when you visited the same url?

Yes, i do see the error in both my provided link and your.

> If yes, could you tell me how you got to that page?

If you meant "how you got to https://tanstack.com/virtual/latest page" - the link is available at main https://tanstack.com/ page on library card.

P.S. now noticed, that the same problem is at https://tanstack.com/ranger/latest

**Comment by fulopkovacs** [comment]
Woah, this is an interesting one. I can't see the issue for any of these urls (I tested it on multiple devices and browsers):
- https://tanstack.com/virtual/latest
- https://tanstack.com/ranger/latest
<img width="600" alt="image" src="https://github.com/TanStack/tanstack.com/assets/43729152/f1a99d09-7b12-4c09-bba4-7cb92892e850">
<img width="600" alt="image" src="https://github.com/TanStack/tanstack.com/assets/43729152/623ea751-bb8b-4935-8c16-d947afcd0d01">

I simply assumed that by `https://tanstack.com/virtual/latest` meant the examples for virtual, like https://tanstack.com/virtual/latest/docs/framework/react/examples/simple. 😆 

Could you check these links in an incognito tab? We had some `301 - Moved permanently` in the code base before, and recently we've reorganized the docs. I don't remember these routes being affected, but we should check this just to be sure.

**Comment by kosovojs** [comment]
it doesn't work incognito mode. checked all major Windows browsers (firefox, chrome, edge), on both Win10 and Win11. also on android chrome, too.

**Comment by fulopkovacs** [comment]
Ahh, thanks for the PR @acusti, now I know which preview we're talking about. 😅 I'll review the PR!
