### ISSUE TITLE
`https://tanstack.com` Site root is throwing authentication errors

### ISSUE THREAD

**Issue by luke-hagar-sp** [TanStack/tanstack.com#177]
First, there is an `Unknown error`, that appears to have the below content embedded in the markup:
```
{
  "root": {
    "error": "AUTHENTICATION_REQUIRED",
    "message": "You should provide valid api key to perform this operation",
    "statusCode": 401
  }
}

```

![image](https://github.com/TanStack/tanstack.com/assets/98849695/2e5684d7-63f2-4239-82fc-79044f0c245b)

The page then refreshes to show the `Unexpected Server Error` which appears to be a 500 with the below response:

![image](https://github.com/TanStack/tanstack.com/assets/98849695/d7ddd81d-3c81-4660-8300-35d85a8bbd07)

**Comment by luke-hagar-sp** [comment]
Navigating directly to `https://tanstack.com/form/latest` was working for me a moment ago, but now its giving me this
![image](https://github.com/TanStack/tanstack.com/assets/98849695/db53517b-06f9-4c9d-8ed4-524bcf51afa9)

**Comment by crutchcorn** [comment]
We're aware of this issue (as of a few moments ago) and are investigating

**Comment by crutchcorn** [comment]
The TanStack site is back up!

https://tanstack.com/

We had to do some hacky stuff to sidestep problems with an API, but we'll have a longer-term fix soon
