### ISSUE TITLE
some head tag is unusual in 'code splitting' on tanstack router

### ISSUE THREAD

**Issue by loopy-lim** [TanStack/tanstack.com#185]
![스크린샷 2024-02-13 오전 12 51 45](https://github.com/TanStack/tanstack.com/assets/45393030/c8a1ff9d-d83a-4eab-b7e8-15046481fe69)

'example' tag is `h3` and 'before' tag is `h4`

I think that why `head tag`'s display css is `inline-block`

so I suggest to change from `inline-block` to `block` on [this code]( https://github.com/TanStack/tanstack.com/blame/00383fac6e3d5251e0b63469aedaf52bb14ba1ea/app/components/RenderMarkdown.tsx#L33)

**Comment by SeanCassiere** [comment]
This has been fixed.
