### ISSUE TITLE
Destination urls in search are broken in Router docs

### ISSUE THREAD

**Issue by Arvin7** [TanStack/tanstack.com#187]
## How to reproduce:
1. Go to https://tanstack.com/router/latest/docs/framework/react/overview
2. Use the search box in the sidebar to search for anything (e.g. `LinkComponent`)
3. Click on the first result
4. The href is https://tanstack.com/router/v1/docs/api/router/linkComponent which redirects back to the Overview page

## The issue:
The `framework` param is not included in the urls in the search result.

The correct path is: `https://tanstack.com/router/v1/docs/framework/react/api/router/linkComponent`

**Comment by SeanCassiere** [comment]
This has been fixed.
