### ISSUE TITLE
The lastest url in banner don't update after navigation

### ISSUE THREAD

**Issue by chigia001** [TanStack/tanstack.com#191]
When working on adding canonical tag for doc site, I try to use loader result from tanstack.com/app/routes/query.$version.tsx to generate the canonical link.

This work fine for SSR inital response, but when user naivate to different page using the menu the redirect URL is not update.

In context of adding canonical link, this is not an issue as we only need this for bot.

But I believe the version banner should be up to date with the current url.

**Comment by SeanCassiere** [comment]
Closed the linked PR with:
