### ISSUE TITLE
Website has Devtools

### ISSUE THREAD

**Issue by Inshiku-Han** [TanStack/tanstack.com#201]
Is this Devtools intended?

<img width="1920" alt="image" src="https://github.com/TanStack/tanstack.com/assets/63291908/4bc39461-549b-452f-830f-d81b786f7365">
<img width="1920" alt="image" src="https://github.com/TanStack/tanstack.com/assets/63291908/d6f79da2-a35a-450e-aafa-c9f2baf5d56d">

**Comment by mudasirpandith** [comment]
@Inshiku-Han This is visible only on `/router/*` . May be this is a way to show its usage.

**Comment by tannerlinsley** [comment]
Yes, this is intended.
