### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by ShaharIlany** [TanStack/tanstack.com#206]
https://tanstack.com/query/latest/docs/framework/react/guides/prefetching

Redirects to: `https://tanstack.com/query/latest/docs/framework/react/guides/tkdodos-blog#17-seeding-the-query-cache`
Instead of: `https://tanstack.com/query/latest/docs/framework/react/community/tkdodos-blog#17-seeding-the-query-cache`

<img width="893" alt="image" src="https://github.com/TanStack/tanstack.com/assets/31574996/f9fd0f34-2635-43eb-ba56-f5f578ff7884">

-------

<img width="1430" alt="image" src="https://github.com/TanStack/tanstack.com/assets/31574996/e3dcbe73-bde5-4ae6-8910-ebae05bfd03c">

**Comment by SeanCassiere** [comment]
I believe this is being covered in [PR #7247](https://github.com/TanStack/query/pull/7247/files#diff-fb065d21c5055641cd560b22d450f9ea25f369c24f563fdc46dafae9b9f16e44R442) in the Query repo.

**Comment by SeanCassiere** [comment]
This has since been fixed
