### ISSUE TITLE
bug: incorrect OG image generation

### ISSUE THREAD

**Issue by SeanCassiere** [TanStack/tanstack.com#207]
Cannot confirm if this was the same behaviour prior to this [commit](https://github.com/TanStack/tanstack.com/commit/b8bd868e9cfc3df668979425a76c7c12c2ef85c1), but currently, the opengraph images generated for the documentation routes are all pointed at Form.

See for Query: tanstack.com/query/latest/docs/framework/react/overview - [checker](https://www.opengraph.xyz/url/https%3A%2F%2Ftanstack.com%2Fquery%2Flatest%2Fdocs%2Foverview)
<img width="476" alt="image" src="https://github.com/TanStack/tanstack.com/assets/33615041/54b7f752-0d45-4108-9308-b192a626b5a0">

See for Router: tanstack.com/router/latest/docs/framework/react/overview - [checker](https://www.opengraph.xyz/url/https%3A%2F%2Ftanstack.com%2Frouter%2Flatest%2Fdocs%2Fframework%2Freact%2Foverview)
<img width="474" alt="image" src="https://github.com/TanStack/tanstack.com/assets/33615041/aa850a38-25be-4791-8785-23d37b419659">

**Comment by tannerlinsley** [comment]
We should start generating these with code, but yes, I’ll get this fixed.
