### ISSUE TITLE
Error while running in the development mode

### ISSUE THREAD

**Issue by thevipinmishra** [TanStack/tanstack.com#21]
I just forked and ran the development server.

Got this error on the very first run.

![image](https://user-images.githubusercontent.com/52159805/180641906-8167cc9b-747f-4e18-a876-dde03431bf51.png)

However, the CSS file was generated as I can see in the output, but I still can't access the `localhost:3001`

Also checked the routes folder, can't open any route mentioned there! :(

Is there a different endpoint? Am I missing something?

**Comment by thevipinmishra** [comment]
Also checked the routes folder, can't open any route mentioned there! :(

**Comment by thevipinmishra** [comment]
Looks like my system had some error, I basically restarted my machine and it worked fine.

**Comment by nickmccurdy** [comment]
There seems to be a race condition in the build process.
