### ISSUE TITLE
Website Fails to Render when Microsoft Editor Chrome Extension Installed

### ISSUE THREAD

**Issue by jenewland1999** [TanStack/tanstack.com#215]
Hey Maintainers 👋🏻,

I was visiting the tanstack site to RTFM and I experienced a weird rendering issue where the page was completely blank. Similar to that of #210. I had no issues in an Incognito window so I assumed it was extension related. After a brief process of a elimination I discovered it was the [Microsoft Editor: Spelling & Grammar Checker](https://chromewebstore.google.com/detail/microsoft-editor-spelling/gpaiobkfhnonedkhhfjpmhdalgeoebfa?pli=1) extension causing the issue.

What specifically this extension is doing to cause the website rendering to fail entirely I'm not entirely sure. If you're unfamiliar with the extension it's a glorrified spell and grammar checker. Below I've included all the details I feel might be helpful for both reproducing the issue. 

Do let me know if you need anything further though. 

Peace ✌🏻 

## System details

Device: MacBook Pro 14-inch (Apple M1 Pro)
Arch: ARM64
OS: macOS Sonoma 14.4.1
Browser: Chrome 124.0.6367.62
Extension version: v1.8.1

## Console Logs

<img width="1242" alt="image" src="https://github.com/TanStack/tanstack.com/assets/34895363/37da7232-7cc5-4548-84d8-719a0f9f24a0">
<img width="1241" alt="image" src="https://github.com/TanStack/tanstack.com/assets/34895363/937c1e01-fbb5-48d2-a0f3-00efbb3d918a">

**Comment by SeanCassiere** [comment]
This bugs should now be ironed out.
