### ISSUE TITLE
If switch Framework when on page that doesn't exist on other framework, leads to 404

### ISSUE THREAD

**Issue by GeorgeWL** [TanStack/tanstack.com#216]
I feel like it should instead reroute to index for that section maybe?

e.g. https://tanstack.com/query/latest/docs/framework/react/comparison then switch to "Vue" goes to 404 and url of https://tanstack.com/query/latest/docs/framework/vue/comparison

**Comment by SeanCassiere** [comment]
This is expected behaviour. Since the Vue docs for Query, do not have a comparison page, it leads the user to a 404.

@GeorgeWL if you are willing, I'm sure the folks over at https://github.com/TanStack/query would appreciate contributions towards adding an accurate comparison page.

Closing.
