### ISSUE TITLE
Angular code example for TanStack Table is missing

### ISSUE THREAD

**Issue by jreidgreer** [TanStack/tanstack.com#223]
# Description
On https://tanstack.com/table/latest the `Angular` example under "Take it for a spin!" doesn't work. I don't see this path in the Table's [example folder](https://github.com/TanStack/table/tree/main/examples), so not sure where it is supposed to point.

## Screenshot

<img width="1409" alt="TanStack_Table" src="https://github.com/TanStack/tanstack.com/assets/4984283/a12b8fc4-ebe1-47fe-be9e-730b291ed261">

**Comment by jreidgreer** [comment]
Ah, looks like this should be fixed by the main PR to create an adapter: https://github.com/TanStack/table/pull/5432

**Comment by KevinVandy** [comment]
Angular table doesn't actually exist yet. We thought we were close to shipping, but then the PR got abandoned, but now there's more progress being made again.

**Comment by SeanCassiere** [comment]
This looks to be resolved now.

<img width="1438" alt="image" src="https://github.com/user-attachments/assets/e6b3555e-88f5-4193-a965-30bb104befe5">
