### ISSUE TITLE
Broken/missing Tanstack Store page

### ISSUE THREAD

**Issue by gcbianchi** [TanStack/tanstack.com#225]
This is what happens when I click 'Get started' button on the Tanstack Store project page (it's stuck at this loading state infinitely). Reloading the page gives an empty/blank page (server responds with 404). It does not happen for any other project page.

<img width="1792" alt="Screenshot 2024-05-05 at 7 57 05 am" src="https://github.com/TanStack/tanstack.com/assets/1086684/23fcca5d-32cf-4415-9acd-f3c76a6b4c57">

**Comment by SeanCassiere** [comment]
This is now fixed.
