### ISSUE TITLE
feat: Minor feedback - GridVirtualizerFixed example code can be simplified

### ISSUE THREAD

**Issue by tian-lan-landing** [TanStack/tanstack.com#228]
When setting the odd and even class name to each cell, the current example is like this:
```
               <div
                  key={virtualColumn.key}
                  className={
                    virtualColumn.index % 2
                      ? virtualRow.index % 2 === 0
                        ? 'ListItemOdd'
                        : 'ListItemEven'
                      : virtualRow.index % 2
                        ? 'ListItemOdd'
                        : 'ListItemEven'
                  }
```

<img width="903" alt="image" src="https://github.com/TanStack/tanstack.com/assets/86591280/4bec8d4a-c2a1-4b07-9904-bfaf58c46c03">

It can be simplified like this:
```
                <div
                  key={virtualColumn.key}
                  className={
                    virtualColumn.index % 2 !== virtualRow.index % 2
                        ? 'ListItemOdd'
                        : 'ListItemEven'
                  }
```

<img width="892" alt="image" src="https://github.com/TanStack/tanstack.com/assets/86591280/ed66c53e-0f8e-4c4b-8347-32bb6041a428">

**Comment by SeanCassiere** [comment]
Please report this in the individual project for [TanStack/virtual](https://github.com/TanStack/virtual).
