### ISSUE TITLE
TanStack Auth

### ISSUE THREAD

**Issue by Jay-Karia** [TanStack/tanstack.com#267]
Seamlessly roll authentication in web applications.

**Comment by SeanCassiere** [comment]
Are you looking to contribute a package to the TanStack ecosystem? If so, you may want to reach out to Tanner first on [Discord](https://tlinz.com/discord).

If not, and you are actually looking for auth solutions, then [Clerk](https://go.clerk.com/wOwHtuJ) is a fully-featured authentication partner of TanStack, which you can check out. Not to mention other more manually maintained solutions like Lucia and Authjs.

**Comment by Jay-Karia** [comment]
Not looking for any auth solutions, but just gave a feature request to also provide authentication.

Will talk to Tanner about this.

Thanks
