### ISSUE TITLE
Broken website

### ISSUE THREAD

**Issue by Thisisme1228** [TanStack/tanstack.com#276]
/![Image](https://github.com/user-attachments/assets/349d1079-224a-433d-8484-586826f3a1c1)
Why I can’t access the website in China.

**Comment by johncmunson** [comment]
It's broken for me as well. The whole site. Seems to only be affecting mobile.

**Comment by SeanCassiere** [comment]
@johncmunson you may have been caught mid-release. Trying it now, the website looks to be working fine.

@Thisisme1228 provided that the GitHub CDN and vercel functions aren't restricted in your region, the website should be functioning. Could you please try again?

**Comment by gislerro** [comment]
Same issue when accessing from switzerland
