### ISSUE TITLE
docs: maxPages are missing in the example of useInfiniteQuery docs

### ISSUE THREAD

**Issue by jae-hun-e** [TanStack/tanstack.com#278]
First of all, thank you for providing these good tools. This makes it easy to develop.

I am reporting that some of the changes in v5 have not been applied while reading TanningstackQuery/react docs.

'maxPages' added to v5 are not visible in the InfiniteQuery document usage example. 
I think this could lead to some people moving on without knowing useful features.
![Image](https://github.com/user-attachments/assets/c4333b94-bb5c-473e-bff5-79c1447cee6e)

If you don't mind, can I fix this problem?
thank you

**Comment by SeanCassiere** [comment]
Thanks for coming over to contribute!

Documentation content issues need to be reported to the individual projects so that their maintainers may review and give the go-ahead on any changes.
Please head over to https://github.com/TanStack/query and ask the folks there about this.
