### ISSUE TITLE
Relative links in table/v8/docs/guide don't work

### ISSUE THREAD

**Issue by JulioC** [TanStack/tanstack.com#28]
All relative links in the doc pages for TanStack Table under `Guide` are being resolve relative to `table/v8/docs` instead to `table/v8/docs/guide`. This breaks navigation on most Guide files.

Examples:
- https://tanstack.com/table/v8/docs/guide/features
- https://tanstack.com/table/v8/docs/guide/column-defs

**Comment by tannerlinsley** [comment]
We're aware of it and currently there in't much we can do other than fix them individually. Apparently Remix uses route hierarchy instead of `/` to determine relative links. I don't agree with that API decision, but what can you do.. 🤷‍♂️
