### ISSUE TITLE
router/../routing-concepts: broken link

### ISSUE THREAD

**Issue by jkellogg01** [TanStack/tanstack.com#282]
The link to 'pathless routes' at the top of https://tanstack.com/router/latest/docs/framework/react/guide/routing-concepts links to `#pathless--layout-routes`, but the section about pathless routes is at `#pathless-routes` so the link does nothing.

**Comment by SeanCassiere** [comment]
Thank you for pointing this out. This has since been fixed in https://github.com/TanStack/router/pull/2444.
