### ISSUE TITLE
Inline example code not runnable

### ISSUE THREAD

**Issue by JonNode28** [TanStack/tanstack.com#285]
The inline example code on various pages is not runnable:

![Image](https://github.com/user-attachments/assets/eea85782-31f4-4b8b-98fb-db5740bdecbe)

**Comment by SeanCassiere** [comment]
Which page is this from?

I've tested this out on the landing pages for all the TanStack libraries and have not run into this issue.

The only issue we've had with Stackblitz is on occasions where browser support doesn't allow for the embed node environments that Chrome allows. Perhaps this is a browser compatibility issue?

**Comment by SeanCassiere** [comment]
> Just noticed this only applies to firefox

Figured as much. Until, Stackblitz or the browsers implement a fix, there isn't much that we can do here.
