### ISSUE TITLE
docs: search doesn't work

### ISSUE THREAD

**Issue by tryonelove** [TanStack/tanstack.com#286]
### Describe the bug

Hello,

Seems like search on the docs doesn't work at all.
The search provider seems to be responsible for that, it doesn't return any results in the response body.

### Steps to reproduce

1. Go to https://tanstack.com/query/latest/docs/framework/react/overview
2. Try to search something

### Expected behavior

Search results show up

### Screenshots or Videos

Search results for `useQuery`:
![Image](https://github.com/user-attachments/assets/5bc4adbd-c5bf-47fc-ab41-68d3845bb1d7)
![Image](https://github.com/user-attachments/assets/cf42f8b5-0e25-4780-ae42-f5e9ccb63221)

**Comment by SeanCassiere** [comment]
This may have been a bit of downtime at the time you accessed the website.

Retesting this today it looks to be working.

Normal
![Image](https://github.com/user-attachments/assets/031feb20-3425-4192-ae89-22e32db04d6d)

In incognito
![Image](https://github.com/user-attachments/assets/0abca86a-3065-47e5-8ade-1a3042bf75ec)

We'll be sure to let the folks over at Orama know if we run into further issues like this.
