### ISSUE TITLE
docs: line height for package titles is clipping descender letters

### ISSUE THREAD

**Issue by dosmond** [TanStack/tanstack.com#289]
In these cases we can see that the 'g' in Ranger and the 'y' in Query are being cut off.

![Image](https://github.com/user-attachments/assets/e6cfb32f-2b7b-4084-a8d7-5e419ae18df3)

![Image](https://github.com/user-attachments/assets/c108e320-8e33-4964-8993-b994ebc446d4)

**Comment by SeanCassiere** [comment]
Fixed with #290
