### ISSUE TITLE
Main docs site for Tanstack crashing on visit

### ISSUE THREAD

**Issue by adhanji8** [TanStack/tanstack.com#317]
When I visit:
[https://tanstack.com/start/latest](https://tanstack.com/start/latest)

I'm getting a "gradientText is not defined" error. 

For what it's worth, prior to getting that error, I was trying to view the stackblitz example for Tanstack Start + React Query, but the stackblitz demo seemed to crash. After that, when I refreshed the page a couple times, I started seeing that error. This might be totally unrelated...just thought I'd mention it!

EDIT: happening on other tanstack doc pages too like Tanstack Query
![Image](https://github.com/user-attachments/assets/66f4f30b-98fb-4ea0-9637-b9ba20804c36)

**Comment by julianklumpers** [comment]
same happens for me, the site is down.

**Comment by whiz-terminal** [comment]
Hi @adhanji8 , this is now resolved. I just tried it and seems to be working.

**Comment by ch-shubham** [comment]
Hi @adhanji8 , this is now resolved. I just tried it and seems to be working.

**Comment by adhanji8** [comment]
Awesome, it's working again. Closing.
