### ISSUE TITLE
Website is down - Vercel 404: Deployment Not Found

### ISSUE THREAD

**Issue by amcraig** [TanStack/tanstack.com#319]
<img width="1125" alt="Image" src="https://github.com/user-attachments/assets/0c21c6c0-3530-4836-a638-db3525650f88" />

Hi all, your documentation website is down.

**Comment by tannerlinsley** [comment]
You sure? Clear your cache

**Comment by amcraig** [comment]
It's back up now. I checked about an hour after reporting the issue and it was resolved. 

Thanks for looking into it, just thought I'd report it.
