### ISSUE TITLE
/query/v4/docs/comparison not working

### ISSUE THREAD

**Issue by MatMatias** [TanStack/tanstack.com#33]
[https://tanstack.com/query/v4/docs/comparison](https://tanstack.com/query/v4/docs/comparison) is not working:

![image](https://user-images.githubusercontent.com/38060185/187076682-1ba847ab-bc01-43b8-af5d-70ef04922ad0.png)

**Comment by iicdii** [comment]
Fixed by https://github.com/TanStack/query/pull/4137

**Comment by MatMatias** [comment]
Thanks
