### ISSUE TITLE
The "examples" section doesn't load

### ISSUE THREAD

**Issue by azihassan** [TanStack/tanstack.com#41]
Hi, I was reading the docs and noticed that the examples display an empty black rectangle :

![image](https://user-images.githubusercontent.com/1638227/191115397-18e99d79-0d75-4ad6-a3eb-b3993a1f71e0.png)

The view source link leads to a 404 page. I looked into it and found out that it's missing /react/ in the path. So for example, the "simple" page should redirect to https://github.com/TanStack/query/tree/main/examples/react/simple instead of https://github.com/TanStack/query/tree/main/examples/simple. The sandbox URL has this issue as well.

**Comment by crutchcorn** [comment]
Closing, as this appears to be fixed
