### ISSUE TITLE
Svelte codeblocks aren't supported

### ISSUE THREAD

**Issue by lachlancollins** [TanStack/tanstack.com#63]
Hello, I'm the new maintainer of the svelte-query package. I've noticed that the svelte codeblocks are described as being "bash" even when specified as svelte, and also don't have great syntax highlighting. Is there any way to add in correct processing of svelte?

**Comment by TkDodo** [comment]
it seems that we use `prism-react-renderer` for the `CodeBlock` component:

https://github.com/TanStack/tanstack.com/blob/0bb1f2a9fc09df20e2b9d2f97204236619ef7015/app/components/CodeBlock.tsx#L4-L5

According to [their docs](https://github.com/FormidableLabs/prism-react-renderer#faq), they only support an [arbitrary subset of the languages](https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/vendor/prism/includeLangs.js), and it seems like `svelte` isn't one of them.

if `prismjs` supports it, we can add svelte manually.

**Comment by lachlancollins** [comment]
Looks like the sveltestack query docs used `prism-react-renderer` too and set markdown as the rendering language - I think we can just use that for now :)
