### ISSUE TITLE
Website is down 3/27/23

### ISSUE THREAD

**Issue by swsvindland** [TanStack/tanstack.com#74]
Looks like there might be an issue with the tailwindcss version and generating styles that is causing the website to display nothing.

**Comment by tannerlinsley** [comment]
Loading fine in my tests here. Anyone else confirm this?

Tanner Linsley

**Comment by swsvindland** [comment]
I think I have more info on this. It looks to be fine on chrome, firefox on windows x86-64

On macos arm64, firefox and safari are also fine, but on chrome it just will not finish rendering.

I don't have a x86-64 mac or linux box, so they may be worth testing

**Comment by salicius** [comment]
It not renders examples (react/solid/vue) both on Chrome and Safari:

<img width="1280" alt="Screenshot 2023-04-17 at 6 55 10 PM" src="https://user-images.githubusercontent.com/78569177/232556549-eafe4421-7d29-4085-8dde-73d5cb9b4d2e.png">

**Comment by crutchcorn** [comment]
Closing, as this issue isn't specific enough to debug and the site appears to be loading fine. Please open more issues should anything arise in the future :)
