### ISSUE TITLE
Infinite redirection `/query/v3/docs/vue/overview`

### ISSUE THREAD

**Issue by ferc** [TanStack/tanstack.com#85]
If I'm navigating the Vue docs I could select the `v3` as version, which ends in an endless loop of redirection:
https://tanstack.com/query/v3/docs/vue/overview -> https://tanstack.com/query/v3/docs/vue -> https://tanstack.com/query/v3/docs/vue/overview

<img width="539" alt="Screenshot 2023-05-17 at 3 25 07 PM" src="https://github.com/TanStack/tanstack.com/assets/902031/9b7dad3d-8677-4311-a44a-85b1989671db">

**Comment by fulopkovacs** [comment]
Apparently, there are no Vue docs for `TanStack Query v3`. This is the `config.json` file that is read for `v3`: [`config.json`](https://github.com/TanStack/query/blob/dd3f2a718bdeea282ae12db15e1733b48309cc62/docs/config.json#L9).

**Comment by fulopkovacs** [comment]
This error for `v3` happens to me for every framework except for React and Angular (which doesn't even have docs):
- ❌ https://tanstack.com/query/v3/docs/solid/overview
- ❌ https://tanstack.com/query/v3/docs/vue/overview
- ❌ https://tanstack.com/query/v3/docs/svelte/overview
- ✅ https://tanstack.com/query/v3/docs/react/overview
- ✅ https://tanstack.com/query/v3/docs/angular/overview -> redirects to the react docs

**Comment by crutchcorn** [comment]
@fulopkovacs this might be worth edgecasing so that we can redirect from Vue/Solid/Svelte v3 -> React as well. Any chance you wanna pick up this ticket?

> I know you're already doing a lot, so if not, no worries!

**Comment by fulopkovacs** [comment]
Yeah sure, here you go: https://github.com/TanStack/tanstack.com/pull/140!
