### ISSUE TITLE
nozzle partnership card links to ag-grid partnership article

### ISSUE THREAD

**Issue by llllvvuu** [TanStack/tanstack.com#94]
<img width="493" alt="Screenshot 2023-09-09 at 5 28 04 AM" src="https://github.com/TanStack/tanstack.com/assets/5601392/4fb52f3f-71fe-443e-b969-21e305167e1b">

Issue as of `a964d86`:

https://github.com/TanStack/tanstack.com/blob/a964d864fcc7df99991122842631be4a8e879984/app/routes/index.tsx#L435

I'm not sure the referenced article actually exists: https://github.com/TanStack/tanstack.com/tree/a964d864fcc7df99991122842631be4a8e879984/app/blog

Can probably just remove the "Learn More" if it doesn't.

**Comment by crutchcorn** [comment]
Closing as I believe this is fixed.
